drop database ecommerce;
create database ecommerce;
use ecommerce;

CREATE TABLE USER (
	USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE,
    ROLE VARCHAR(5) NOT NULL CHECK (ROLE IN ('ADMIN', 'USER'))
);

CREATE TABLE CATEGORY (
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ICON VARCHAR(50)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE FLOAT NOT NULL CHECK (PRICE >= 0),
    CATEGORY_ID INT,
    IMAGE VARCHAR(255),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE SET NULL
);

CREATE TABLE STORE_LOCATIONS (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
	LATITUDE  DECIMAL(10, 8),
	LONGITUDE DECIMAL(11, 8),
    LOCATION VARCHAR(255)
);

