INSERT INTO USER (USERNAME, PASSWORD, EMAIL, ROLE) VALUES
('admin1_', '94e18c47da09307ef3e56f4ae0dfc6b0466a2eb2bc3b5eb009bac18de08f302f', 'admin1_@gmail.com', 'ADMIN'), -- username: admin1_, password: admin1_
('user1_', '788390a67bfcb6a21b3747283a93d98b51c4a8d8ba27debcd7dace81df7cb2e1', 'user1_@gmail.com', 'USER'); -- username: user1_, password: user1_

INSERT INTO CATEGORY (NAME, DESCRIPTION, ICON) VALUES  
('Fiction', 'Imaginative storytelling with made-up characters and events, often set in realistic or fantastical worlds.', 'auto_stories'),  
('Non-Fiction', 'Informative and factual writing based on real events, people, or knowledge.', 'menu_book'),  
('Mystery & Thriller', 'Suspenseful stories involving crime, puzzles, or psychological tension.', 'mystery'),  
('Science Fiction & Fantasy', 'Speculative fiction featuring futuristic technology, magic, or fantastical worlds.', 'robot_2'),  
('Romance', 'Stories centered on love, relationships, and emotional journeys.', 'favorite'),  
('Horror', 'Fiction designed to evoke fear, dread, or shock, often with supernatural elements.', 'skull'),  
('Business & Finance', 'Books focused on economics, entrepreneurship, management, and personal finance.', 'monitoring'),  
('Science & Technology', 'Explores scientific topics and technological innovations, from theory to application.', 'science');


INSERT INTO PRODUCT (NAME, AUTHOR, DESCRIPTION, PRICE, CATEGORY_ID, IMAGE) VALUES  
('The Midnight Library', 'Matt Haig', 'A novel about a **library between life and death**, offering infinite choices. The protagonist, *Nora Seed*, finds herself in a magical library where each book represents a different version of her life. As she explores these alternate realities, she discovers what truly matters in life and what makes a life worth living. Through *beautiful prose* and *profound insights*, Haig tackles themes of **regret**, **possibility**, and the **meaning of happiness**. *The Midnight Library* serves as both an **engaging story** and a **philosophical exploration** of the roads not taken.', 12.99, 1, 'products/0.jpg'),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A classic novel about **wealth**, **love**, and the **American Dream**. Set in the *Roaring Twenties*, it follows the mysterious millionaire *Jay Gatsby* and his obsession with *Daisy Buchanan*. Through the eyes of narrator *Nick Carraway*, readers witness the **lavish parties**, **moral emptiness**, and **tragic consequences** of pursuing hollow dreams. Fitzgerald masterfully captures the **disillusionment** of the Jazz Age through *vivid imagery* and *lyrical prose*. A timeless critique of the **corruption of the American Dream** and the **danger of living in the past**.', 10.50, 1, 'products/1.jpg'),
('To Kill a Mockingbird', 'Harper Lee', 'A powerful novel about **race** and **justice** in the American South. Narrated by young *Scout Finch*, the story revolves around her father, *Atticus Finch*, who defends a Black man wrongfully accused of rape in 1930s Alabama. Through Scout''s innocent perspective, Lee examines **deep-rooted prejudice**, **moral complexity**, and the **loss of innocence**. The novel also explores the mysterious neighbor *Boo Radley* and the children''s fascination with him. A compassionate portrayal of **courage in the face of injustice**, and a classic that continues to resonate with readers.', 9.99, 1, 'products/2.jpg'),
('Pride and Prejudice', 'Jane Austen', 'A classic romance novel set in **19th-century England**. The story follows the spirited *Elizabeth Bennet* as she navigates rigid social hierarchies and a complicated relationship with the proud *Mr. Darcy*. Austen brilliantly **satirizes the marriage market** and **social expectations** through *witty dialogue* and *keen psychological insight*. Explores themes of **reputation**, **class**, and the **dangers of first impressions**. A richly layered novel full of **memorable characters** and **timeless wisdom**.', 8.99, 1, 'products/3.jpg'),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'A deep dive into **human evolution and culture**. Harari charts the course from the emergence of *Homo sapiens* in Africa to today. Covers key transformations: the **Cognitive Revolution**, **Agricultural Revolution**, and **Scientific Revolution**. He offers **provocative theories** on how shared myths—from religions to corporations—enable **large-scale cooperation**. An **interdisciplinary** and *thought-provoking* exploration of humanity’s past and potential futures.', 18.50, 2, 'products/4.jpg'),
('Educated', 'Tara Westover', 'A memoir of growing up in a **survivalist family** in rural Idaho. Raised by *fundamentalist parents* who distrusted formal institutions, Westover never attended school until she was 17. Through **self-education**, she entered Brigham Young University and later earned a **PhD from Cambridge**. Her story examines the **price of education**, **family loyalty**, and **personal transformation**. A powerful testament to the **transformative power of knowledge** and the **courage to forge your own path**.', 16.75, 2, 'products/5.jpg'),
('The Power of Habit', 'Charles Duhigg', 'An exploration of how **habits shape our lives**. Duhigg presents *cutting-edge scientific research* explaining why habits exist and how they can be changed. The book introduces the **habit loop**—cue, routine, reward—and demonstrates how understanding this pattern can transform **individual behaviors**, **organizational outcomes**, and **societal patterns**. Through compelling case studies—from *Michael Phelps* to *Starbucks* and *Target*—Duhigg illustrates the principles of **habit formation and modification**. He also explores how habits influenced major social movements like the **civil rights movement**. A practical framework for anyone looking to change behavior and unlock personal or professional growth.', 14.99, 2, 'products/6.jpg'),
('Atomic Habits', 'James Clear', 'A guide to **building good habits** and **breaking bad ones**. Clear presents a practical framework focused on *small, incremental changes* rather than dramatic transformations. The book explains how **tiny habits compound** over time to produce remarkable results using the *Four Laws of Behavior Change*: **make it obvious**, **make it attractive**, **make it easy**, and **make it satisfying**. With examples from Olympic athletes, artists, and business leaders, Clear demonstrates how **small changes lead to big success**. Incorporating insights from **biology**, **psychology**, and **neuroscience**, the book offers a proven system for achieving long-term improvement.', 17.99, 2, 'products/7.jpg'),
('Gone Girl', 'Gillian Flynn', 'A **psychological thriller** about a mysterious disappearance. When *Amy Dunne* vanishes on her fifth wedding anniversary, her husband *Nick* becomes the prime suspect. The story alternates between Nick''s perspective and Amy''s diary, creating an intricate puzzle where **truth is elusive**. Flynn explores the dark dynamics of a **toxic marriage**, the media circus around missing women, and manipulative behavior. With **unreliable narrators**, **shocking twists**, and a chilling critique of gender roles, this novel redefined the modern thriller and remains a *benchmark in the genre*.', 14.25, 3, 'products/8.jpg'),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A gripping mystery featuring a journalist and a hacker. *Mikael Blomkvist*, a disgraced reporter, is hired to solve the **decades-old disappearance** of a young woman. He partners with *Lisbeth Salander*, a brilliant yet deeply troubled hacker with a traumatic past and photographic memory. Set in Sweden''s elite circles and remote regions, the investigation uncovers **dark family secrets** and **serial crimes**. Larsson blends **detective fiction**, **social critique**, and complex character studies to explore themes of **corruption**, **misogyny**, and **institutional failure**. The novel introduced one of modern literature''s most iconic heroines.', 13.99, 3, 'products/9.jpg'),
('The Silent Patient', 'Alex Michaelides', 'A **psychological thriller** centered on a woman who stops speaking. *Alicia Berenson*, a famous painter, murders her husband and becomes mute. *Theo Faber*, a psychotherapist obsessed with her case, takes a job at the psychiatric facility where she''s confined. As Theo investigates, **deep secrets emerge**, and his motives become blurred. Michaelides crafts a suspenseful narrative exploring **trauma**, **art**, and **psychotherapy**. With a twist ending that forces readers to *reconsider everything*, this debut novel is a masterclass in tension and misdirection.', 15.49, 3, 'products/10.jpg'),
('The Da Vinci Code', 'Dan Brown', 'A **mystery thriller** involving secret societies and ancient codes. Harvard symbologist *Robert Langdon* is summoned to the Louvre Museum after a murder victim is arranged like **Da Vinci''s Vitruvian Man**. Joined by cryptologist *Sophie Neveu*, Langdon follows a trail of hidden clues across Europe to uncover a **2,000-year-old religious secret**. The novel blends **art history**, **religious symbolism**, and **conspiracy theories** about the Holy Grail and Mary Magdalene. Brown''s fast-paced style and cliff-hanger chapter endings make this a gripping intellectual thriller that sparked global debate.', 16.25, 3, 'products/11.jpg'),
('Dune', 'Frank Herbert', 'A **sci-fi epic** set on the desert planet *Arrakis*, source of the powerful spice melange. *Paul Atreides*, heir to a noble family, must navigate betrayal, survival, and destiny among the native Fremen after his family loses power. Herbert crafts an immersive universe of **ecological**, **religious**, and **political intrigue**, exploring themes of **environmentalism**, **resource control**, and **messianic prophecy**. Featuring a deeply constructed world and rich character arcs, *Dune* remains one of the most influential science fiction novels ever written.', 16.99, 4, 'products/12.jpg'),
('The Hobbit', 'J.R.R. Tolkien', 'A **fantasy adventure** following *Bilbo Baggins*, a quiet hobbit drawn into a quest to reclaim a dwarven kingdom from the dragon *Smaug*. Alongside *Gandalf* and thirteen dwarves, Bilbo faces trolls, goblins, and the mysterious *Gollum*. Through this whimsical yet epic journey, Bilbo transforms from reluctant traveler to courageous hero. Tolkien balances humor and warmth with deep themes of **friendship**, **courage**, and **greed**, laying the foundation for modern fantasy literature.', 13.75, 4, 'products/13.jpg'),
('The Name of the Wind', 'Patrick Rothfuss', 'A **fantasy novel** chronicling the life of *Kvothe*, a gifted young man with a tragic past and a destiny shrouded in legend. Told through a frame narrative, Kvothe recounts his journey from traveling performer to orphan, to a student at a magical university. Rothfuss introduces a **scientific magic system**, rich cultural world-building, and poetic prose. Themes of **storytelling**, **myth**, and **the search for truth** make this an epic tale filled with heart, mystery, and lyrical beauty.', 14.50, 4, 'products/14.jpg'),
('Ender''s Game', 'Orson Scott Card', 'A **science fiction classic** about child prodigies trained for war. *Ender Wiggin*, a brilliant and isolated boy, is sent to Battle School to prepare for a looming alien threat. In zero-gravity war games, Ender proves a tactical genius while grappling with the psychological toll of manipulation and isolation. Card explores **ethics**, **leadership**, and the **moral complexity of war**, asking what sacrifices are acceptable for survival. A powerful tale about growing up, empathy, and the cost of victory.', 11.99, 4, 'products/15.jpg'),
('The Notebook', 'Nicholas Sparks', 'A **timeless romance** told through the eyes of an elderly man reading from a notebook to a woman with dementia. The story follows *Noah Calhoun* and *Allie Nelson*, young lovers torn apart by class and war but reunited by fate. Sparks intertwines past and present, exploring themes of **enduring love**, **memory**, and **life''s fragility**. With emotional depth and lyrical writing, the novel captures a powerful love story that spans decades and defies illness and time.', 10.99, 5, 'products/16.jpg'),
('Me Before You', 'Jojo Moyes', 'A **romantic drama** exploring love, loss, and choice. *Louisa Clark* takes a job caring for *Will Traynor*, a wealthy man left quadriplegic after an accident. Their relationship evolves from frustration to affection as Lou tries to show Will that life is still worth living. Moyes tackles **ethical dilemmas**, **assisted suicide**, and **emotional growth**, balancing humor with heartbreak. A deeply human story about dignity, autonomy, and the impact we have on each other’s lives.', 12.75, 5, 'products/17.jpg'),
('It Ends With Us', 'Colleen Hoover', 'A **romantic novel** dealing with **domestic violence** and **resilience**. *Lily Bloom* starts a relationship with neurosurgeon *Ryle Kincaid*, but troubling parallels to her parents'' abusive marriage begin to surface. With the return of her first love, *Atlas Corrigan*, Lily is forced to make difficult choices. Hoover combines emotional honesty with a compelling narrative that refuses to romanticize toxicity. Inspired by the author''s personal history, this story speaks to those seeking strength in difficult circumstances.', 13.99, 5, 'products/18.jpg'),
('The Rosie Project', 'Graeme Simsion', 'A **romantic comedy** about *Don Tillman*, a brilliant yet socially awkward geneticist who creates a questionnaire to find his ideal wife. His plan is upended by *Rosie*, who fails every test but brings spontaneity and love into his rigid world. As Don helps Rosie search for her biological father, he begins to question what makes relationships meaningful. Simsion’s novel is full of **humor**, **heart**, and **insight into neurodiversity**, making it a quirky and touching love story.', 11.25, 5, 'products/19.jpg'),
('It', 'Stephen King', 'A **horror epic** centered on a malevolent entity that haunts the town of *Derry, Maine*. Known as *Pennywise the Dancing Clown*, the shapeshifting being feeds on children''s fears. The story follows the *Losers'' Club*, a group of kids who battle It both in childhood and again as adults. King blends **psychological terror**, **supernatural horror**, and **emotional trauma**, exploring the impact of fear, friendship, and memory. A chilling masterpiece that defined a generation of horror fiction.', 15.99, 6, 'products/20.jpg'),
('Dracula', 'Bram Stoker', 'The quintessential vampire novel that introduced the world to the enigmatic Count Dracula, a figure who has since become a cultural icon. Set in the late 19th century, the story unfolds through letters, diary entries, and newspaper clippings, chronicling the Count''s move from Transylvania to England. There, he stalks his victims, including the brave Mina Harker and her circle of determined defenders, led by Professor Van Helsing. Stoker''s gothic masterpiece delves into themes of fear, desire, and the clash between modernity and ancient evil. This timeless tale laid the foundation for countless vampire stories that followed.', 10.50, 6, 'products/21.jpg'),
('The Shining', 'Stephen King', 'A gripping horror novel that follows Jack Torrance, a struggling writer and recovering alcoholic, as he takes a job as the winter caretaker of the isolated Overlook Hotel. Accompanied by his wife Wendy and young son Danny, who possesses psychic abilities known as "the shining," the family soon discovers the hotel''s dark past. As supernatural forces awaken, Jack''s descent into madness threatens to destroy them all, fueled by the malevolent presence within the hotel''s walls. King weaves a tale of isolation, addiction, and paranormal terror that keeps readers on edge from start to finish. Widely regarded as a horror classic, it explores the fragility of the human mind under extreme pressure.', 14.75, 6, 'products/22.jpg'),
('House of Leaves', 'Mark Z. Danielewski', 'A mind-bending horror novel that defies conventional storytelling with its labyrinthine narrative and experimental typography. The book centers on a young family who move into a house that seems to grow larger on the inside than it appears from the outside, sparking a descent into obsession and dread. Through layered narratives—including a manuscript by a blind old man and footnotes by a troubled tattoo artist—Danielewski crafts an unsettling exploration of space, perception, and reality. The text''s unusual formatting mirrors the characters'' unraveling sanity, drawing readers into its disorienting depths. This cult classic challenges and rewards those brave enough to navigate its haunting, unconventional pages.', 17.99, 6, 'products/23.jpg'),
('Rich Dad Poor Dad', 'Robert Kiyosaki', 'A transformative personal finance book that contrasts the money-management philosophies of two father figures in Kiyosaki''s life: his educated but financially struggling "poor dad" and the entrepreneurial "rich dad." Through practical lessons, it teaches readers how to build wealth by investing in assets, understanding financial statements, and thinking beyond a traditional paycheck. The book emphasizes financial independence, urging readers to take control of their economic futures rather than relying on employers or the government. Kiyosaki''s straightforward, conversational style makes complex concepts accessible to beginners and seasoned investors alike. Now a modern classic, it has inspired millions to rethink their approach to money and success.', 11.50, 7, 'products/24.jpg'),
('The Lean Startup', 'Eric Ries', 'A groundbreaking guide for entrepreneurs and innovators looking to build successful businesses in an uncertain world. Ries introduces the "lean" methodology, which emphasizes rapid experimentation, customer feedback, and iterative product development to minimize waste and maximize efficiency. The book draws on real-world examples to show how startups can adapt quickly to changing markets and customer needs. It''s a must-read for anyone aiming to launch a company or bring new ideas to life, offering practical tools like the "build-measure-learn" loop. Since its release, it has become a cornerstone of modern entrepreneurial thinking.', 16.25, 7, 'products/25.jpg'),
('Think and Grow Rich', 'Napoleon Hill', 'A timeless self-help book that distills the secrets of success from interviews with over 500 of the early 20th century''s most accomplished individuals, including Andrew Carnegie and Henry Ford. Hill outlines a philosophy of achievement based on desire, faith, persistence, and the power of the mind to shape reality. The book offers practical steps—such as creating a definite plan and forming a "mastermind" group—to turn dreams into tangible results. Its motivational tone and universal principles have made it a perennial favorite among those seeking personal and financial growth. Decades after its publication, it remains a powerful guide for aspiring achievers.', 14.99, 7, 'products/26.jpg'),
('The Millionaire Next Door', 'Thomas J. Stanley', 'A fascinating study of America''s wealthy, revealing that many millionaires live surprisingly modest lives rather than flaunting extravagant wealth. Based on extensive research, Stanley and co-author William Danko uncover the habits and mindsets that enable ordinary people to accumulate extraordinary fortunes. The book highlights traits like frugality, disciplined saving, and strategic investing, debunking myths about the "typical" rich person. It''s an eye-opening read for anyone interested in understanding how financial success is often built quietly over time. This insightful work challenges readers to rethink their assumptions about money and status.', 18.99, 7, 'products/27.jpg'),
('The Code Breaker', 'Walter Isaacson', 'A compelling biography of Jennifer Doudna, the Nobel Prize-winning scientist who co-developed CRISPR, the revolutionary gene-editing technology. Isaacson chronicles her journey from a curious child in Hawaii to a trailblazer in biotechnology, weaving in the broader story of how CRISPR is reshaping medicine and ethics. The book explores the science behind this breakthrough, its potential to cure diseases, and the moral dilemmas it raises about altering human DNA. Written with Isaacson''s signature clarity and narrative flair, it''s both a personal portrait and a deep dive into a world-changing innovation. It''s a must-read for anyone curious about the future of science and humanity.', 20.99, 8, 'products/28.jpg'),
('Brief Answers to the Big Questions', 'Stephen Hawking', 'A thought-provoking collection of essays addressing some of the universe''s greatest mysteries, penned by the legendary physicist Stephen Hawking. Drawing on his decades of research, Hawking tackles questions like "Is there a God?", "Can we predict the future?", and "Will we survive on Earth?" with clarity and wit. Published posthumously, the book reflects his lifelong passion for unraveling cosmic enigmas and making science accessible to all. It blends profound insights with Hawking''s personal reflections, offering a fitting capstone to his extraordinary career. This inspiring work invites readers to ponder humanity''s place in the vast expanse of space and time.', 19.50, 8, 'products/29.jpg');

INSERT INTO STORE_LOCATIONS (NAME, LATITUDE, LONGITUDE, LOCATION) VALUES 
('STORE 1','10.7732467','106.6571912', 'Truong Dai hoc Bach Khoa, 268 Ly Thuong Kiet, Phuong 14, Quan 10, TP. HCM'), 
('STORE 2','10.8805585','106.8005154', 'Truong Dai hoc Bach Khoa, Di An, Binh Duong'), 
('STORE 3','10.7722799','106.6574359', '280 Ly Thuong Kiet, Phuong 14, Quan 10, TP. HCM');