INSERT INTO USER (FNAME, LNAME, USERNAME, PASSWORD, PHONE_NUMBER, EMAIL, LOCATION, ROLE) VALUES
('John', 'Doe', 'johndoe', 'password123', '1234567890', 'johndoe@example.com', 'New York, USA', 'USER'),
('Jane', 'Smith', 'janesmith', 'securepass', '1234567891', 'janesmith@example.com', 'Los Angeles, USA', 'USER'),
('Alice', 'Brown', 'aliceb', 'alicepass', '1234567892', 'aliceb@example.com', 'Chicago, USA', 'USER'),
('Bob', 'Johnson', 'bobj', 'bobjohn123', '1234567893', 'bobj@example.com', 'Houston, USA', 'USER'),
('Charlie', 'Williams', 'charliew', 'charliepass', '1234567894', 'charliew@example.com', 'Phoenix, USA', 'USER'),
('David', 'Miller', 'davidm', 'davidpass', '1234567895', 'davidm@example.com', 'Philadelphia, USA', 'USER'),
('Emma', 'Davis', 'emmad', 'emma123', '1234567896', 'emmad@example.com', 'San Antonio, USA', 'USER'),
('Frank', 'Wilson', 'frankw', 'frankpass', '1234567897', 'frankw@example.com', 'San Diego, USA', 'USER'),
('Grace', 'Moore', 'gracem', 'gracepass', '1234567898', 'gracem@example.com', 'Dallas, USA', 'USER'),
('Henry', 'Taylor', 'henryt', 'henrypass', '1234567899', 'henryt@example.com', 'San Jose, USA', 'USER'),
('Ivy', 'Anderson', 'ivya', 'ivypass', '1234567800', 'ivya@example.com', 'Austin, USA', 'USER'),
('Jack', 'Thomas', 'jackt', 'jackpass', '1234567801', 'jackt@example.com', 'Jacksonville, USA', 'USER'),
('Kelly', 'Jackson', 'kellyj', 'kellypass', '1234567802', 'kellyj@example.com', 'Fort Worth, USA', 'USER'),
('Liam', 'White', 'liamw', 'liampass', '1234567803', 'liamw@example.com', 'Columbus, USA', 'USER'),
('Mia', 'Harris', 'miah', 'miapass', '1234567804', 'miah@example.com', 'Charlotte, USA', 'USER'),
('Nathan', 'Martin', 'nathanm', 'nathanpass', '1234567805', 'nathanm@example.com', 'San Francisco, USA', 'USER'),
('Olivia', 'Lee', 'olivial', 'oliviapass', '1234567806', 'olivial@example.com', 'Indianapolis, USA', 'USER'),
('Paul', 'Perez', 'paulp', 'paulpass', '1234567807', 'paulp@example.com', 'Seattle, USA', 'USER'),
('Quinn', 'Hall', 'quinnh', 'quinnpass', '1234567808', 'quinnh@example.com', 'Denver, USA', 'USER'),
('Rachel', 'Young', 'rachely', 'rachelpass', '1234567809', 'rachely@example.com', 'Washington, USA', 'ADMIN'),
('Samuel', 'Baker', 'samuelb', 'samuelpass', '1234567810', 'samuelb@example.com', 'Boston, USA', 'ADMIN'),
('Tina', 'Scott', 'tinascott', 'tinapass', '1234567811', 'tinascott@example.com', 'Miami, USA', 'ADMIN'),
('Victor', 'Adams', 'victora', 'victorpass', '1234567812', 'victora@example.com', 'Atlanta, USA', 'ADMIN');

INSERT INTO CATEGORY (NAME, ICON) VALUES  
('Fiction', 'bi bi-book'),  
('Non-Fiction', 'bi bi-book-fill'),  
('Mystery & Thriller', 'bi bi-incognito'),  
('Science Fiction & Fantasy', 'bi bi-rocket-takeoff'),  
('Romance', 'bi bi-heart'),  
('Horror', 'bi bi-emoji-surprise'),  
('Business & Finance', 'bi bi-bar-chart'),  
('Science & Technology', 'bi bi-laptop');

INSERT INTO PRODUCT (NAME, AUTHOR, DESCRIPTION, PRICE, CATEGORY_ID, IMAGE, SALES, QUANTITY) VALUES  
('The Midnight Library', 'Matt Haig', 'A novel about a library between life and death, offering infinite choices. The protagonist, Nora Seed, finds herself in a magical library where each book represents a different version of her life. As she explores these alternate realities, she discovers what truly matters in life and what makes a life worth living. Through beautiful prose and profound insights, Haig tackles themes of regret, possibility, and the meaning of happiness. The Midnight Library serves as both an engaging story and a philosophical exploration of the roads not taken.', 12.99, 1, 'products/0.jpg', 50000, 120),  
('The Great Gatsby', 'F. Scott Fitzgerald', 'A classic novel about wealth, love, and the American Dream. Set in the Roaring Twenties, it follows the mysterious millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan. Through the eyes of narrator Nick Carraway, readers witness the lavish parties, moral emptiness, and ultimately tragic consequences of pursuing hollow dreams. Fitzgerald masterfully captures the disillusionment of the Jazz Age through vivid imagery and lyrical prose. The novel serves as a timeless critique of the corruption of the American Dream and the danger of living in the past.', 10.50, 1, 'products/1.jpg', 68000, 150),  
('To Kill a Mockingbird', 'Harper Lee', 'A powerful novel about race and justice in the American South. Narrated by young Scout Finch, the story revolves around her father, lawyer Atticus Finch, who defends a Black man wrongfully accused of rape in 1930s Alabama. Through Scout''s innocent perspective, Lee examines deep-rooted prejudice, moral complexity, and the loss of innocence. The novel also explores the mysterious neighbor Boo Radley and the children''s fascination with him. Its compassionate portrayal of courage in the face of injustice has made it an enduring classic that continues to resonate with readers decades after its publication.', 9.99, 1, 'products/2.jpg', 87000, 180),  
('Pride and Prejudice', 'Jane Austen', 'A classic romance novel set in 19th-century England. The story follows the spirited Elizabeth Bennet as she navigates the rigid social hierarchies of her time while developing a complicated relationship with the proud Mr. Darcy. Austen brilliantly satirizes the marriage market and social expectations through witty dialogue and keen psychological insight. The novel explores themes of reputation, class, and the dangers of first impressions and hasty judgments. Beyond the central romance, Austen creates a rich tapestry of memorable characters whose foibles and virtues reflect the complex society of Regency England.', 8.99, 1, 'products/3.jpg', 92000, 200),  
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'A deep dive into human evolution and culture. Harari charts the course of human history from the emergence of Homo sapiens in Africa to the present day, examining how our species came to dominate the planet. The book explores the Cognitive Revolution, Agricultural Revolution, and Scientific Revolution as pivotal moments that transformed human societies. Harari presents provocative theories about how shared myths and fictional constructs—from religions to corporations to human rights—enable large-scale human cooperation. His interdisciplinary approach combines insights from biology, anthropology, economics, and philosophy to offer a fresh perspective on humanity''s past and potential futures.', 18.50, 2, 'products/4.jpg', 75000, 140),  
('Educated', 'Tara Westover', 'A memoir about growing up in a survivalist family in rural Idaho. Westover recounts her upbringing by fundamentalist parents who distrusted formal education, modern medicine, and government institutions. Despite never attending school until age seventeen, she taught herself enough to gain admission to Brigham Young University and eventually earned a PhD from Cambridge. The memoir details her struggle to reconcile her loyalty to family with her desire for knowledge and self-determination. Westover''s powerful narrative examines the price of education and the pain of family estrangement. Her story stands as a testament to the transformative power of education and the strength required to break from one''s origins.', 16.75, 2, 'products/5.jpg', 65000, 130),  
('The Power of Habit', 'Charles Duhigg', 'An exploration of how habits shape our lives. Duhigg presents cutting-edge scientific research explaining why habits exist and how they can be changed. The book introduces the habit loop—cue, routine, reward—and demonstrates how understanding this pattern can transform individual behaviors, organizational outcomes, and societal patterns. Through compelling case studies ranging from Olympic swimmer Michael Phelps to Starbucks and Target, Duhigg illustrates the principles of habit formation and modification. He also explores how habits played a crucial role in social movements like the civil rights movement. The book provides practical frameworks for readers to apply these insights to their own lives and organizations.', 14.99, 2, 'products/6.jpg', 54000, 120),  
('Atomic Habits', 'James Clear', 'A guide to building good habits and breaking bad ones. Clear presents a practical framework for improving every day by focusing on small, incremental changes rather than dramatic transformations. The book explains how tiny changes compound over time to produce remarkable results through the four laws of behavior change: make it obvious, make it attractive, make it easy, and make it satisfying. Using compelling examples from Olympic gold medalists, award-winning artists, and business leaders, Clear demonstrates how small habits lead to extraordinary results. He also incorporates insights from biology, psychology, and neuroscience to explain why the system works and how readers can apply it to their own lives. The book offers a proven method for mastering the small behaviors that lead to remarkable results.', 17.99, 2, 'products/7.jpg', 99000, 160),  
('Gone Girl', 'Gillian Flynn', 'A psychological thriller about a mysterious disappearance. When Amy Dunne vanishes on her fifth wedding anniversary, her husband Nick becomes the prime suspect as evidence of his guilt mounts. The narrative alternates between Nick''s perspective and Amy''s diary entries, creating an intricate puzzle where truth becomes increasingly elusive. Flynn masterfully explores the dark dynamics of a toxic marriage and the media frenzy surrounding a missing beautiful woman. The novel features one of literature''s most memorable unreliable narrators and shocking plot twists that force readers to constantly reassess their assumptions. Its razor-sharp examination of gender roles, sociopathic behavior, and the performance of identity has made it a landmark in contemporary thriller fiction.', 14.25, 3, 'products/8.jpg', 62000, 110),  
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A gripping mystery about a journalist and a hacker. Disgraced financial reporter Mikael Blomkvist is hired by industrial magnate Henrik Vanger to solve the 40-year-old disappearance of his niece. Blomkvist teams up with Lisbeth Salander, a brilliant but troubled computer hacker with a photographic memory and a traumatic past. Set against the backdrop of Sweden''s financial world and isolated northern regions, the investigation uncovers dark family secrets and a pattern of serial killings. Larsson weaves together themes of corruption, misogyny, and institutional failure through complex characters and intricate plotting. The novel combines elements of classic detective fiction with scathing social critique and creates one of modern fiction''s most iconic female protagonists.', 13.99, 3, 'products/9.jpg', 70000, 125),  
('The Silent Patient', 'Alex Michaelides', 'A psychological thriller about a woman who stops speaking. Famous painter Alicia Berenson seemingly had a perfect life until she shot her husband five times in the face and then never spoke another word. Psychotherapist Theo Faber becomes obsessed with uncovering the mystery behind her silence and takes a job at the secure psychiatric facility where she''s been confined. As Theo delves deeper into Alicia''s case, his motivations become increasingly complex, and dangerous secrets begin to surface. Michaelides crafts a taut narrative that explores themes of trauma, art as expression, and the nature of psychotherapy itself. The novel''s shocking twist ending forces readers to reevaluate everything they thought they knew about the characters and their motivations.', 15.49, 3, 'products/10.jpg', 89000, 150),  
('The Da Vinci Code', 'Dan Brown', 'A mystery thriller involving secret societies and ancient codes. Harvard symbologist Robert Langdon is summoned to the Louvre Museum to examine a murder victim arranged like Da Vinci''s Vitruvian Man, launching him into a race across Europe to uncover a 2000-year-old religious secret. Accompanied by cryptologist Sophie Neveu, Langdon follows a trail of clues hidden in famous artworks while evading both police and a determined albino assassin. The novel blends art history, religious symbolism, and conspiracy theories about the Holy Grail and Mary Magdalene''s role in Christian history. Brown''s fast-paced narrative style and cliff-hanger chapter endings create a reading experience that combines intellectual puzzles with action-thriller momentum. The controversial religious themes sparked international debate and fueled the book''s phenomenal commercial success.', 16.25, 3, 'products/11.jpg', 110000, 170),  
('Dune', 'Frank Herbert', 'A sci-fi epic set in a desert world filled with politics and mysticism. The novel follows Paul Atreides, heir to a noble family tasked with ruling the harsh desert planet Arrakis, the only source of the most valuable substance in the universe—the spice melange. When treachery removes his family from power, Paul must embrace his destiny as a messianic figure among Arrakis''s native Fremen people. Herbert creates an immersive universe with complex ecological, religious, and political systems that serve as allegories for oil politics, environmental concerns, and religious fanaticism. The novel features richly developed characters navigating a world where careful attention to water conservation shapes an entire culture. Herbert''s masterwork combines adventure with philosophical depth, establishing a template for science fiction that continues to influence the genre decades later.', 16.99, 4, 'products/12.jpg', 88000, 140),  
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy adventure about Bilbo Baggins and a dragon. The comfortable, unambitious hobbit is reluctantly swept into a quest to reclaim the dwarf kingdom of Erebor from the fearsome dragon Smaug. Guided by the wizard Gandalf and accompanied by thirteen dwarves, Bilbo encounters trolls, goblins, elves, and the creature Gollum, from whom he acquires a mysterious ring. Tolkien crafts a journey of personal growth as Bilbo transforms from a timid homebody to a brave and resourceful hero. The novel establishes the rich mythology and detailed world-building that would later expand in The Lord of the Rings trilogy. Written with humor and warmth, the book balances whimsical fairy-tale elements with themes of courage, friendship, and the corrupting influence of greed.', 13.75, 4, 'products/13.jpg', 93000, 150),  
('The Name of the Wind', 'Patrick Rothfuss', 'A fantasy novel about a legendary figure named Kvothe. Told as an autobiography, the story follows Kvothe from his childhood in a troupe of traveling performers to his years as a near-feral orphan and his eventual entrance into a prestigious magical university. The frame narrative reveals that the now-disguised Kvothe is recounting his life story to a Chronicler over three days, with this novel covering the first day. Rothfuss crafts an intricate magic system based on scientific principles and creates a richly detailed world with its own mythology, music, and cultural traditions. The novel explores themes of storytelling itself, the nature of heroism, and how legends are born from kernels of truth. Kvothe''s pursuit of knowledge about the mysterious Chandrian drives the narrative through adventure, tragedy, and romance.', 14.50, 4, 'products/14.jpg', 76000, 135),  
('Ender''s Game', 'Orson Scott Card', 'A sci-fi novel about child soldiers training in space. In a future where Earth has survived two invasions by insectoid aliens called "Buggers," the military identifies and trains gifted children to become commanders. Six-year-old Ender Wiggin is selected for Battle School, where he excels in zero-gravity war games despite being isolated and manipulated by his adult supervisors. Card creates a psychologically intense narrative focusing on strategy, leadership, and the moral implications of warfare. The novel explores themes of empathy and communication across seemingly unbridgeable differences. Ender''s journey examines the cost of victory and raises questions about whether the ends justify the means. The book''s examination of how children are shaped by adult agendas remains relevant decades after its publication.', 11.99, 4, 'products/15.jpg', 85000, 145),  
('The Notebook', 'Nicholas Sparks', 'A timeless romance novel about love and memory. The story begins with an elderly man reading from a notebook to a woman in a nursing home, telling the tale of Noah Calhoun and Allie Nelson, who fall in love in 1940s North Carolina despite coming from different social classes. Separated by Allie''s disapproving parents and World War II, they reunite years later when Allie, now engaged to another man, sees a newspaper article about Noah''s restored plantation house. Sparks weaves together their passionate summer romance with the poignant present-day narrative of an elderly couple facing the challenges of dementia. The novel explores themes of enduring love, social divisions, and the power of memory to transcend time and illness. Through lyrical prose and emotional depth, Sparks creates a love story that has resonated with millions of readers worldwide.', 10.99, 5, 'products/16.jpg', 45000, 100),  
('Me Before You', 'Jojo Moyes', 'A romance novel exploring love and personal choices. Louisa Clark, an ordinary girl with limited prospects, takes a job caring for Will Traynor, a once-ambitious banker left quadriplegic after an accident. Initially antagonistic, their relationship develops as Lou tries to show Will that life is still worth living despite his physical limitations. Moyes tackles difficult ethical questions about quality of life, assisted suicide, and what we owe to those we love. The novel balances heartbreaking moments with humor and warmth as Lou''s colorful personality draws Will out of his depression. Beyond the central relationship, the book examines class differences in British society and how tragedy affects not just individuals but entire families. The story challenges readers to consider what makes a meaningful life and the extent to which we should respect others'' most difficult choices.', 12.75, 5, 'products/17.jpg', 67000, 120),  
('It Ends With Us', 'Colleen Hoover', 'A romance novel about love, resilience, and choices. Lily Bloom, who grew up witnessing domestic violence between her parents, opens her own business and begins a relationship with neurosurgeon Ryle Kincaid. Their passionate connection is complicated by Ryle''s aversion to relationships and the reappearance of Lily''s first love, Atlas Corrigan. As Lily''s relationship with Ryle intensifies, she begins to see troubling parallels to her parents'' marriage. Hoover crafts a nuanced narrative that examines the cycle of abuse and the difficult decisions faced by those who experience intimate partner violence. Through alternating timelines and Lily''s teenage diary entries to Ellen DeGeneres, the novel provides context for her emotional development and personal history. The book''s unflinching honesty about domestic violence, informed by Hoover''s own family history, has resonated deeply with readers seeking stories that don''t romanticize toxic relationships.', 13.99, 5, 'products/18.jpg', 97000, 140),  
('The Rosie Project', 'Graeme Simsion', 'A romantic comedy about an eccentric genetics professor. Don Tillman, a brilliant but socially awkward scientist, decides to find a wife by creating a detailed questionnaire to identify the perfect partner. His plans go awry when he meets Rosie Jarman, a spontaneous bartender who fails every criterion on his list but captivates him nonetheless. As Don helps Rosie search for her biological father through DNA testing—a project that utilizes his scientific expertise—he finds his rigid routines and worldview increasingly challenged. Simsion creates a protagonist whose literal-minded perspective provides both humor and insight into social conventions neurotypical people take for granted. The novel balances laugh-out-loud moments with touching observations about human connection and the unpredictability of love. Don''s journey illustrates how sometimes the people who don''t match our preconceptions can be exactly who we need.', 11.25, 5, 'products/19.jpg', 62000, 110),
('It', 'Stephen King', 'A chilling horror novel centered on a shape-shifting entity that preys on the children of Derry, Maine. The story follows a group of childhood friends, known as the Losers'' Club, who confront their deepest fears embodied by the sinister Pennywise the Dancing Clown. Decades later, the group reunites as adults to face the lingering evil that still haunts their small town. King masterfully blends psychological terror with visceral horror, exploring themes of trauma, memory, and the power of friendship. This sprawling tale remains one of his most iconic works, captivating readers with its eerie atmosphere and unforgettable characters.', 15.99, 6, 'products/20.jpg', 90000, 160),  
('Dracula', 'Bram Stoker', 'The quintessential vampire novel that introduced the world to the enigmatic Count Dracula, a figure who has since become a cultural icon. Set in the late 19th century, the story unfolds through letters, diary entries, and newspaper clippings, chronicling the Count''s move from Transylvania to England. There, he stalks his victims, including the brave Mina Harker and her circle of determined defenders, led by Professor Van Helsing. Stoker''s gothic masterpiece delves into themes of fear, desire, and the clash between modernity and ancient evil. This timeless tale laid the foundation for countless vampire stories that followed.', 10.50, 6, 'products/21.jpg', 85000, 150),  
('The Shining', 'Stephen King', 'A gripping horror novel that follows Jack Torrance, a struggling writer and recovering alcoholic, as he takes a job as the winter caretaker of the isolated Overlook Hotel. Accompanied by his wife Wendy and young son Danny, who possesses psychic abilities known as "the shining," the family soon discovers the hotel''s dark past. As supernatural forces awaken, Jack''s descent into madness threatens to destroy them all, fueled by the malevolent presence within the hotel''s walls. King weaves a tale of isolation, addiction, and paranormal terror that keeps readers on edge from start to finish. Widely regarded as a horror classic, it explores the fragility of the human mind under extreme pressure.', 14.75, 6, 'products/22.jpg', 94000, 170),  
('House of Leaves', 'Mark Z. Danielewski', 'A mind-bending horror novel that defies conventional storytelling with its labyrinthine narrative and experimental typography. The book centers on a young family who move into a house that seems to grow larger on the inside than it appears from the outside, sparking a descent into obsession and dread. Through layered narratives—including a manuscript by a blind old man and footnotes by a troubled tattoo artist—Danielewski crafts an unsettling exploration of space, perception, and reality. The text''s unusual formatting mirrors the characters'' unraveling sanity, drawing readers into its disorienting depths. This cult classic challenges and rewards those brave enough to navigate its haunting, unconventional pages.', 17.99, 6, 'products/23.jpg', 130000, 180),  
('Rich Dad Poor Dad', 'Robert Kiyosaki', 'A transformative personal finance book that contrasts the money-management philosophies of two father figures in Kiyosaki''s life: his educated but financially struggling "poor dad" and the entrepreneurial "rich dad." Through practical lessons, it teaches readers how to build wealth by investing in assets, understanding financial statements, and thinking beyond a traditional paycheck. The book emphasizes financial independence, urging readers to take control of their economic futures rather than relying on employers or the government. Kiyosaki''s straightforward, conversational style makes complex concepts accessible to beginners and seasoned investors alike. Now a modern classic, it has inspired millions to rethink their approach to money and success.', 11.50, 7, 'products/24.jpg', 67000, 130),  
('The Lean Startup', 'Eric Ries', 'A groundbreaking guide for entrepreneurs and innovators looking to build successful businesses in an uncertain world. Ries introduces the "lean" methodology, which emphasizes rapid experimentation, customer feedback, and iterative product development to minimize waste and maximize efficiency. The book draws on real-world examples to show how startups can adapt quickly to changing markets and customer needs. It''s a must-read for anyone aiming to launch a company or bring new ideas to life, offering practical tools like the "build-measure-learn" loop. Since its release, it has become a cornerstone of modern entrepreneurial thinking.', 16.25, 7, 'products/25.jpg', 54000, 120),  
('Think and Grow Rich', 'Napoleon Hill', 'A timeless self-help book that distills the secrets of success from interviews with over 500 of the early 20th century''s most accomplished individuals, including Andrew Carnegie and Henry Ford. Hill outlines a philosophy of achievement based on desire, faith, persistence, and the power of the mind to shape reality. The book offers practical steps—such as creating a definite plan and forming a "mastermind" group—to turn dreams into tangible results. Its motivational tone and universal principles have made it a perennial favorite among those seeking personal and financial growth. Decades after its publication, it remains a powerful guide for aspiring achievers.', 14.99, 7, 'products/26.jpg', 93000, 140),  
('The Millionaire Next Door', 'Thomas J. Stanley', 'A fascinating study of America''s wealthy, revealing that many millionaires live surprisingly modest lives rather than flaunting extravagant wealth. Based on extensive research, Stanley and co-author William Danko uncover the habits and mindsets that enable ordinary people to accumulate extraordinary fortunes. The book highlights traits like frugality, disciplined saving, and strategic investing, debunking myths about the "typical" rich person. It''s an eye-opening read for anyone interested in understanding how financial success is often built quietly over time. This insightful work challenges readers to rethink their assumptions about money and status.', 18.99, 7, 'products/27.jpg', 46000, 100),  
('The Code Breaker', 'Walter Isaacson', 'A compelling biography of Jennifer Doudna, the Nobel Prize-winning scientist who co-developed CRISPR, the revolutionary gene-editing technology. Isaacson chronicles her journey from a curious child in Hawaii to a trailblazer in biotechnology, weaving in the broader story of how CRISPR is reshaping medicine and ethics. The book explores the science behind this breakthrough, its potential to cure diseases, and the moral dilemmas it raises about altering human DNA. Written with Isaacson''s signature clarity and narrative flair, it''s both a personal portrait and a deep dive into a world-changing innovation. It''s a must-read for anyone curious about the future of science and humanity.', 20.99, 8, 'products/28.jpg', 30000, 80),  
('Brief Answers to the Big Questions', 'Stephen Hawking', 'A thought-provoking collection of essays addressing some of the universe''s greatest mysteries, penned by the legendary physicist Stephen Hawking. Drawing on his decades of research, Hawking tackles questions like "Is there a God?", "Can we predict the future?", and "Will we survive on Earth?" with clarity and wit. Published posthumously, the book reflects his lifelong passion for unraveling cosmic enigmas and making science accessible to all. It blends profound insights with Hawking''s personal reflections, offering a fitting capstone to his extraordinary career. This inspiring work invites readers to ponder humanity''s place in the vast expanse of space and time.', 19.50, 8, 'products/29.jpg', 65000, 110);
INSERT INTO CART (USERNAME, PRODUCT_ID) VALUES  
('johndoe', 1),  
('johndoe', 5),  
('johndoe', 12),  
('aliceb', 3),  
('aliceb', 8),  
('aliceb', 15),  
('bobj', 2),  
('bobj', 7),  
('bobj', 14),  
('emmad', 6),  
('emmad', 10),  
('emmad', 18),  
('charliew', 4),  
('charliew', 9),  
('charliew', 16),  
('davidm', 11),  
('davidm', 13),  
('davidm', 19),  
('gracem', 17),  
('gracem', 20);

INSERT INTO TRANSACTION (USERNAME, TRANSACTION_DATE) VALUES  
('johndoe', '2025-02-20 10:15:30'),  
('aliceb', '2025-02-21 14:30:45'),  
('bobj', '2025-02-22 09:10:20'),  
('emmad', '2025-02-22 16:45:55'),  
('charliew', '2025-02-23 11:05:10'),  
('davidm', '2025-02-23 18:20:40'),  
('gracem', '2025-02-24 08:55:25'),  
('johndoe', '2025-02-24 19:30:50'),  
('aliceb', '2025-02-25 12:15:35'),  
('bobj', '2025-02-25 21:40:15'),  
('emmad', '2025-02-26 07:25:05'),  
('charliew', '2025-02-26 15:50:30'),  
('davidm', '2025-02-27 13:05:20'),  
('gracem', '2025-02-27 22:10:10'),  
('johndoe', '2025-02-28 09:40:55'),  
('aliceb', '2025-02-28 17:35:45'),  
('bobj', '2025-02-28 10:50:30'),  
('emmad', '2025-02-28 20:15:25'), 
('charliew', '2025-03-01 11:45:10'),  
('davidm', '2025-03-01 18:55:40');



INSERT INTO TRANSACTION_CONTAIN (TRANSACTION_ID, PRODUCT_ID, QUANTITY) VALUES  
(1, 3, 2),  
(1, 7, 1),  
(2, 5, 1),  
(2, 12, 3),  
(3, 8, 2),  
(3, 15, 1),  
(4, 2, 1),  
(4, 6, 2),  
(5, 9, 1),  
(5, 14, 1),  
(6, 4, 2),  
(6, 11, 3),  
(7, 10, 1),  
(7, 18, 2),  
(8, 1, 2),  
(8, 16, 1),  
(9, 13, 1),  
(9, 19, 2),  
(10, 20, 1),  
(10, 17, 1),  
(11, 3, 1),  
(11, 5, 2),  
(12, 7, 1),  
(12, 8, 3),  
(13, 2, 2),  
(13, 6, 1),  
(14, 10, 2),  
(14, 15, 1),  
(15, 9, 1),  
(15, 14, 2),  
(16, 4, 1),  
(16, 11, 2),  
(17, 1, 3),  
(17, 16, 1),  
(18, 13, 2),  
(18, 19, 1),  
(19, 20, 1),  
(19, 17, 2),  
(20, 12, 1),  
(20, 3, 1);

INSERT INTO STORE_LOCATIONS (API_LOCATION) VALUES 
('40.7128,-74.0060'),  -- New York
('34.0522,-118.2437'), -- Los Angeles
('37.7749,-122.4194'); -- San Francisco